migrated to the new web template for browser projects
inrupt/solid-ui-react-example-project pull request #34
Opened 2021-06-29 14:36 UTC by norbert989

2021-06-29 16:36 UTC, ajacksified requested changes
Looks good, just one minor change.

2021-06-30 09:08 UTC, norbert989 commented on components/loginForm/index.jsx
>    const [idp, setIdp] = useState("https://inrupt.net");
Updated, it is already set to `https://broker.pod.inrupt.com` in the template so all good. I just took the one used in the example app when refactoring.

2021-06-30 09:22 UTC, VirginiaBalseiro approved these changes

2021-06-30 18:58 UTC, ajacksified approved these changes

2021-07-05 07:53 UTC, merged